apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xi6jn0p00-java-quarkus
  janus-idp.io/tekton: xi6jn0p00-java-quarkus
  backstage.io/kubernetes-id: xi6jn0p00-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xi6jn0p00-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
